services:
  - type: worker
    name: spambot
    runtime: docker
    repo: https://github.com/TUO_USERNAME/spambot
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DISPLAY
        value: :99
    schedule: "0 */6 * * *"
    autoDeploy: true
    plan: free
